# Generated by Django 3.0.5 on 2020-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
